django_gramm/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


app_name = 'django_gramm'

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import PostsListView, PostCreateView


app_name = 'posts'

urlpatterns = [
    path('', PostsListView.as_view(), name="list"),
    path('new-post/', PostCreateView.as_view(), name="new-post"),
]

users/urls.py
from django.urls import path
from .views import RegisterView, CustomLoginView, LogoutView, ConfigurateView, ProfileView
from .forms import LoginForm
app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, next_page='/users/profile/<str:username>/',
                                           template_name='users/login.html',
                                           authentication_form=LoginForm), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('configurate/', ConfigurateView.as_view(), name='configurate'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile')
]

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Django_Gramm
{% endblock %}

{% block content %}
    <h1>DjangoGramm</h1>
        <p>It is a popular social network and mobile application for sharing photos and videos,
 which allows users to create, edit
 and share multimedia content with friends and followers.
 Launched in 2024, DjangoGramm is quickly becoming one of the most popular applications,
 especially among young audiences, and is now a key platform for visual content,
 personal branding, marketing and social interaction.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav>
        <a href="/">🏠</a> |
        <a href="/posts">📰</a> |
        <a href="/posts/new-post/">new post</a> |
        {% if user.is_authenticated %}
        <a href="/users/profile/<str:username>/">profile</a> |
        <a href="/users/configurate">Conf</a> |
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" aria-label="User Logout" title="User Logout">Logout</button>
            </form>

        {% else %}
            <a href="/users/login">Login</a> |
            <a href="/users/register">Registration</a>
        {% endif %}

    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>