django_gramm/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


app_name = 'django_gramm'

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('users/', include('users.urls')),
    path('posts/', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import PostsListView, PostCreateView


app_name = 'posts'

urlpatterns = [
    path('', PostsListView.as_view(), name="list"),
    path('new-post/', PostCreateView.as_view(), name="new-post"),
]

users/urls.py
from django.urls import path
from .views import RegisterView, CustomLoginView, LogoutView, ConfigurateView, ProfileView
from .forms import LoginForm
app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, next_page='/users/profile/<str:username>/',
                                           template_name='users/login.html',
                                           authentication_form=LoginForm), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('configurate/', ConfigurateView.as_view(), name='configurate'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile')
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=75)
    images = models.ImageField(upload_to='post_images')
    tags = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.tags = ''.join([tag if tag.startswith('#') else '#' + tag for tag in self.tags.split()])
        super(Post, self).save(*args, **kwargs)

posts/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'images', 'tags']

posts/views.py
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from .forms import CreatePost


class PostsListView(ListView):
    model = Post
    template_name = 'posts/posts_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by('-date')


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = CreatePost
    template_name = 'posts/post_new.html'
    login_url = '/users/login/'
    success_url = reverse_lazy('posts:list')

    def form_valid(self, form):
        newpost = form.save(commit=False)
        newpost.author = self.request.user
        newpost.save()
        return super().form_valid(form)

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
   New Post
{% endblock %}

{% block content %}
    <section>
        <h1>New Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form.as_p}}
            <button class="form-submit">Add Post</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% block title %}
{{ post.title }}
{% endblock title %}
{% block content %}
<section>
    {% for post in posts %}
    <article class="post">
         <img
            class="banner"
            src="{{ post.images.url }}"
            alt="{{ post.title }}"
        />
        <h1>{{ post.title }}</h1>
        <h2>{{ post.tags }}</h2>
        <h3>{{ post.date }} by <a href="{% url 'users:profile' username=post.author.username %}">
                {{post.author }}
            </a>
        </h3>
    </article>
     {% endfor %}
    </section>
{% endblock content %}